project:
  type: website
  output-dir: site
  execute-dir: project

website:
  title: "Course Slides"
  navbar:
    left:
      - href: index.qmd
        text: Home
webr:
  cell-options:
    autorun: true
    fig-width: 11
    fig-height: 5
    
execute:
  freeze: auto